version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev -- --host
    ports:
      - '5173:5173'
    networks:
      - jenkins_default
    volumes:
      - '.:/app'
      - '/app/node_modules'

networks:
  jenkins_default:
    external: true